# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(688, 778)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("favicon.bmp")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.topFrame = QtGui.QFrame(self.centralwidget)
        self.topFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.topFrame.setObjectName(_fromUtf8("topFrame"))
        self.gridLayout = QtGui.QGridLayout(self.topFrame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.topFrame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.topFrame)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton_submit = QtGui.QPushButton(self.topFrame)
        self.pushButton_submit.setObjectName(_fromUtf8("pushButton_submit"))
        self.gridLayout.addWidget(self.pushButton_submit, 0, 2, 1, 1)
        self.pushButton_cancel = QtGui.QPushButton(self.topFrame)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.gridLayout.addWidget(self.pushButton_cancel, 0, 3, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.topFrame)
        self.progressBar.setEnabled(False)
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 4)
        self.gridLayout_2.addWidget(self.topFrame, 0, 0, 1, 2)
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(291, 571))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_2.addWidget(self.textBrowser, 1, 0, 2, 1)
        self.mangaIMG = QtGui.QGraphicsView(self.centralwidget)
        self.mangaIMG.setEnabled(False)
        self.mangaIMG.setMinimumSize(QtCore.QSize(256, 421))
        self.mangaIMG.setObjectName(_fromUtf8("mangaIMG"))
        self.gridLayout_2.addWidget(self.mangaIMG, 1, 1, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.tlabelName = QtGui.QLabel(self.frame)
        self.tlabelName.setObjectName(_fromUtf8("tlabelName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.tlabelName)
        self.lEditName = QtGui.QLineEdit(self.frame)
        self.lEditName.setEnabled(False)
        self.lEditName.setObjectName(_fromUtf8("lEditName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lEditName)
        self.tlabelAltName = QtGui.QLabel(self.frame)
        self.tlabelAltName.setObjectName(_fromUtf8("tlabelAltName"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.tlabelAltName)
        self.lEditAltName = QtGui.QLineEdit(self.frame)
        self.lEditAltName.setEnabled(False)
        self.lEditAltName.setObjectName(_fromUtf8("lEditAltName"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lEditAltName)
        self.lEditReleaseYear = QtGui.QLineEdit(self.frame)
        self.lEditReleaseYear.setEnabled(False)
        self.lEditReleaseYear.setObjectName(_fromUtf8("lEditReleaseYear"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lEditReleaseYear)
        self.tlabelReleaseStatus = QtGui.QLabel(self.frame)
        self.tlabelReleaseStatus.setObjectName(_fromUtf8("tlabelReleaseStatus"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.tlabelReleaseStatus)
        self.lEditStatus = QtGui.QLineEdit(self.frame)
        self.lEditStatus.setEnabled(False)
        self.lEditStatus.setObjectName(_fromUtf8("lEditStatus"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lEditStatus)
        self.tlabelAuthor = QtGui.QLabel(self.frame)
        self.tlabelAuthor.setObjectName(_fromUtf8("tlabelAuthor"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.tlabelAuthor)
        self.lEditAuthor = QtGui.QLineEdit(self.frame)
        self.lEditAuthor.setEnabled(False)
        self.lEditAuthor.setObjectName(_fromUtf8("lEditAuthor"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lEditAuthor)
        self.tlabelReleaseYear = QtGui.QLabel(self.frame)
        self.tlabelReleaseYear.setObjectName(_fromUtf8("tlabelReleaseYear"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.tlabelReleaseYear)
        self.gridLayout_2.addWidget(self.frame, 2, 1, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelTargetFolder = QtGui.QLabel(self.frame_2)
        self.labelTargetFolder.setObjectName(_fromUtf8("labelTargetFolder"))
        self.horizontalLayout.addWidget(self.labelTargetFolder)
        self.comboSaveFolder = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboSaveFolder.sizePolicy().hasHeightForWidth())
        self.comboSaveFolder.setSizePolicy(sizePolicy)
        self.comboSaveFolder.setMinimumSize(QtCore.QSize(411, 0))
        self.comboSaveFolder.setEditable(True)
        self.comboSaveFolder.setObjectName(_fromUtf8("comboSaveFolder"))
        self.horizontalLayout.addWidget(self.comboSaveFolder)
        self.toolButtonSaveFolder = QtGui.QToolButton(self.frame_2)
        self.toolButtonSaveFolder.setObjectName(_fromUtf8("toolButtonSaveFolder"))
        self.horizontalLayout.addWidget(self.toolButtonSaveFolder)
        self.gridLayout_2.addWidget(self.frame_2, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 688, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setMinimumSize(QtCore.QSize(1, 18))
        self.statusbar.setMouseTracking(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit_Ctrl_Q = QtGui.QAction(MainWindow)
        self.actionQuit_Ctrl_Q.setObjectName(_fromUtf8("actionQuit_Ctrl_Q"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionQuit_Ctrl_Q)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "mangareader.net - Manga Downloader", None))
        self.label.setText(_translate("MainWindow", "Please enter the name of the manga", None))
        self.pushButton_submit.setText(_translate("MainWindow", "Submit", None))
        self.pushButton_cancel.setText(_translate("MainWindow", "Cancel", None))
        self.tlabelName.setText(_translate("MainWindow", "Name: ", None))
        self.tlabelAltName.setText(_translate("MainWindow", "Alternate Name: ", None))
        self.tlabelReleaseStatus.setText(_translate("MainWindow", "Status: ", None))
        self.tlabelAuthor.setText(_translate("MainWindow", "Author:", None))
        self.tlabelReleaseYear.setText(_translate("MainWindow", "Release Year: ", None))
        self.labelTargetFolder.setText(_translate("MainWindow", "Target Folder: ", None))
        self.toolButtonSaveFolder.setText(_translate("MainWindow", "...", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionQuit_Ctrl_Q.setText(_translate("MainWindow", "Quit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

